# Jekyll Configuration for "Reactive: A React Book for the Reluctant"

title: "Reactive"
description: "A React Book for the Reluctant - A complete React education disguised as a 21-chapter complaint"
author: Claude (AI)
baseurl: "/React-is-Awful"
url: "https://cloudstreet-dev.github.io"

# Theme - Using custom theme
# theme: jekyll-theme-minimal
# remote_theme: pages-themes/minimal@v0.2.0

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - BANTER.md
  - ABOUT.md

# Collections for book chapters
collections:
  chapters:
    output: true
    permalink: /:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "default"

# Navigation order (chapters)
navigation:
  - title: "Home"
    url: "/"
  - title: "Table of Contents"
    url: "/01-table-of-contents"
  - title: "Introduction"
    url: "/02-introduction"
  - title: "1. Why React Exists"
    url: "/03-chapter-why-react-exists"
  - title: "2. JavaScript Fatigue"
    url: "/04-chapter-javascript-fatigue"
  - title: "3. The Virtual DOM"
    url: "/05-chapter-virtual-dom-lie"
  - title: "4. JSX"
    url: "/06-chapter-jsx-abomination"
  - title: "5. Components"
    url: "/07-chapter-components-everywhere"
  - title: "6. State Management"
    url: "/08-chapter-state-management-hell"
  - title: "7. Hooks"
    url: "/09-chapter-hooks-magic"
  - title: "8. useEffect"
    url: "/10-chapter-effects-footguns"
  - title: "9. Props Drilling"
    url: "/11-chapter-props-drilling"
  - title: "10. Patterns & Anti-patterns"
    url: "/12-chapter-patterns-antipatterns"
  - title: "11. Performance"
    url: "/13-chapter-performance-myths"
  - title: "12. Testing"
    url: "/14-chapter-testing-nightmare"
  - title: "13. The Ecosystem"
    url: "/15-chapter-tooling-ecosystem"
  - title: "14. Building a Real App"
    url: "/16-chapter-real-world-app"
  - title: "15. Alternatives"
    url: "/17-chapter-alternatives-grass"
  - title: "16. Acceptance"
    url: "/18-chapter-acceptance"
  - title: "Conclusion"
    url: "/19-conclusion"
  - title: "Appendix"
    url: "/20-appendix-resources"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jemoji

# SEO
logo:
tagline: "A React Book for the Reluctant"
